[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor"

[env]
ESP_LOG = "INFO"
# ESP_HAL_CONFIG_PSRAM_MODE = "quad"

[build]
rustflags = ["-C", "link-arg=-nostartfiles", "-Z", "threads=8"]

target = "xtensa-esp32-none-elf"

[unstable]
build-std = ["alloc", "core"]
